language: perl
perl: "5.28"
os:
  - linux
dist: xenial
addons:
  apt:
    packages:
      - aspcud
      - libgnomecanvas2-dev
      - libgtk2.0-dev
      - libgtksourceview2.0-dev
      - cvc3
      - z3

cache:
  directories:
    - $HOME/perl5
    - $HOME/.opam
    - /usr/local/bin

env:
  global:
    - WP_TIMEOUT=15
    - WP_PROCESSES=2

# Environment setup before test script. Runs for each build
before_install:
  - sudo apt-get update -qq
  - sudo wget --no-clobber http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/cvc4-1.6-x86_64-linux-opt -O /usr/local/bin/cvc4 || true
  - sudo chmod +x /usr/local/bin/cvc4
  - sudo wget --no-clobber https://github.com/ocaml/opam/releases/download/2.0.4/opam-2.0.4-x86_64-linux -O /usr/local/bin/opam || true
  - sudo chmod +x /usr/local/bin/opam
  - opam init --auto-setup --disable-sandboxing --compiler=4.06.1
  - opam install --yes depext

install:
  - opam update
  - opam upgrade --yes
  - opam depext --yes --noninteractive --install frama-c.18.0 why3.0.88.3 alt-ergo menhir
  - opam pin add why3 0.88.3
  - opam pin add frama-c 18.0
  - eval $(opam config env); why3 config --detect
  - cd ../; wget http://coccinelle.lip6.fr/distrib/coccinelle-1.0.7.tar.gz; tar xf coccinelle-1.0.7.tar.gz; cd coccinelle-1.0.7; autoconf && ./configure --prefix=/usr/local/ && make && sudo make install; cd ../Contiki-NG
  - cd ../; git clone https://github.com/evdenis/spec-utils; cd spec-utils; cpanm --quiet --notest --installdeps .; cd ../Contiki-NG

script:
  - git remote set-branches --add origin $TRAVIS_BRACH
  - git fetch
  - git diff --name-only --diff-filter=AM $TRAVIS_COMMIT_RANGE | grep '\.\(c\|h\|spec\)$' | grep lib | sed -e 's/^/--module /' | tr '\n' ' ' | tee modified_files.txt
  - |
    if [ ! -s modified_files.txt ] || ! grep -q -v '\.spec' modified_files.txt; then
       echo --module $(pwd)/os/lib/ > modified_files.txt
    fi
  - eval $(opam config env); ../spec-utils/bin/extricate --type contiki --config $(pwd)/verif/contiki_extricate.conf --done $(pwd)/verif/contiki_status.conf --kernel $(pwd) $(cat modified_files.txt)
  - ../spec-utils/scripts/compare_verdicts $(pwd)/verif/verdicts.txt $(pwd)/verif/new_verdicts.txt
